version: '3.2'

services:

  recebeai-gestaoentregasdb:

    image: mysql:latest

    container_name: recebeai-gestaoentregasdb

    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: recebeai
      MYSQL_PASSWORD: recebeaipassword
      MYSQL_DATABASE: gestaoentregasdb

    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
