version: '3'

services:

  recebeai-rabbitmq:
    extends:
      file: ./recebeai-infraestructure/recebeai-rabbitmq/docker-compose.yml
      service: recebeai-rabbitmq

  recebeai-gestaoentregasdb:
    extends:
      file: ./recebeai-infraestructure/recebeai-gestaoentregasdb/docker-compose.yml
      service: recebeai-gestaoentregasdb

  recebeai-gestaocompras:
    container_name: recebeai-gestaocompras
    build:
      context: ./recebeai-gestaocompras
      dockerfile: Dockerfile
    ports:
      - "8080:8080"